config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }
  get 'pages/home'

  root 'pages#home'

  resources :users, only: [:show, :index]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username, :current_password, :age, :bio, :gender)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
  	@users = User.all
  end

  def show
  end

  private

  def set_user
  	@user = User.find_by(username: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Stukbook", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Timeline</a></li>
        <li><%= link_to "People", users_path%></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
               <%= gravatar_tag current_user.email, size: 20 %><%= current_user.username %>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profile", user_path(current_user.username)%></li>
              <li><a href="#">Friends</a></li>
              <li> <%= link_to "Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li> <%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <% else %>
          <li> <%= link_to "Login", new_user_session_path %> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stukbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/header" %>
  <% flash.each do |type, message| %>
  	<div class="alert alert-info fade-in">
  		<button class="close" data-dismiss="alert">x</button>
  		<%= message %>
  	</div>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/users/_user.html.erb
<div class="col-md-3">
	<div class="thumbnail">
	<%= link_to user_path(user.username) do %>
		<%= gravatar_tag user.email, size: 200 %>
		<% end %>
	</div>

	<div class="caption">
		<h3><%= user.username %></h3>
		<p>Friendship Actions</p>
	</div>
</div>

app/views/users/index.html.erb
<div class="jumbotron text-center">
	<h2>People</h2>
	
	<div class="btn-group" role="group" aria-label="Default Button Groups">
		<button type="button" class="btn btn-default">Everyone</button>	
		<button type="button" class="btn btn-default">Friends</button>	
		<button type="button" class="btn btn-default">Requests</button>	
		<button type="button" class="btn btn-default">Pending</button>	
	</div>
</div>

<div class="container">
	<div class="row">
		<%= render @users %>
	</div>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
	<div class="container">
		
		<div class="row">
			
			<div class="col-md-4">
				<%= gravatar_tag @user.email, size: 200 %>		
			</div>
			
			<div class="col-md-4">
				<h3><%= @user.username %></h3>
				<p>Age: <%= @user.age %></p>
				<p>Gender: <%= @user.gender %></p>
			</div>
			
			<div class="col-md-4">
				<h3> Who am I </h3>
				<small><%= @user.bio %></small>
			</div>
		
		</div>
	</div>
</div>